# Generated by Django 5.2.8 on 2026-09-01 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['slug'], name='sellers_slug_1d9b08_idx'),
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['verification_status'], name='sellers_verific_ae6c91_idx'),
        ),
    ]
